### ISSUE TITLE
Créer un paquet AppImage

### ISSUE THREAD

**Issue by pierreporte** [pierreporte/bornographe#13]
C’est le meilleur choix pour distribuer simplement un logiciel sous Linux. Pour le moment, j’ai mis en place une machine virtuelle sous Ubuntu 12.04 qui servira de base à la génération du paquet lui-même. J’ai des difficultés à générer un fichier correct pour le moment. Il est peut-être possible d’obtenir de l’aide de @probonopd.

**Comment by durandarno** [comment]
[bornrep.zip](https://github.com/pierreporte/bornrep/files/679682/bornrep.zip)
Voilà ;)

**Comment by probonopd** [comment]
Merci d'avoir fourni un paquet debian. J'ai essayé de l'utiliser comme un ingrédient pour un AppImage mais python3-pyx n'existe pas dans les anciennes versions LTS d'Ubuntu.

Pouvez-vous plutôt fournir un téléchargement pour une version basée sur virtualenv ou cx_freeze que je peux utiliser comme ingrédients pour AppImage?

**Comment by pierreporte** [comment]
@probonopd You can download the version packaged with cx_freeze here: https://github.com/pierreporte/bornrep/releases/tag/v1.0

**Comment by probonopd** [comment]
Trying to run this on ubuntu-16.04-desktop-amd64.iso I get

```
$ '/home/me/Downloads/bornrep/bornrep' 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "bornrep.py", line 26, in <module>
  File "/home/thomas/Projets/bornographe/interface.py", line 72, in __init__
  File "/home/thomas/Projets/bornographe/interface.py", line 234, in génerer
  File "/home/thomas/Projets/bornographe/graphique.py", line 90, in __init__
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1454, in preamble
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1245, in preamble
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1195, in do_preamble
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1404, in do_start
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1156, in do_start
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/config.py", line 190, in Popen
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
  File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'latex'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1022, in _cleanup
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1211, in do_finish
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1395, in go_typeset
  File "/home/thomas/Projets/bornographe/lib/python3.5/site-packages/pyx/text.py", line 1071, in _execute
AttributeError: 'SingleLatexRunner' object has no attribute 'texoutput'
```
So this cx_freeze thing is not entirely working...

**Comment by pierreporte** [comment]
Despite the fact that the cx_freeze packages are theoretically standalone, you still have to install some LaTeX utilities because PyX uses it to generate text. For Ubuntu, the latex-base package should work. I don’t really like this dependency and I am planning to move to pyCairo.
