### ISSUE TITLE
exécutable Windows ? 

### ISSUE THREAD

**Issue by ghost** [pierreporte/bornographe#16]
La question peut paraître saugrenue mais si quelqu'un veut l'utiliser sous Windows, ce serait pas mal de proposer des binaires ou une méthode pour les fabriquer

**Comment by pierreporte** [comment]
À priori tout est multiplateforme. Il suffit d’installer les dépendances et d’exécuter les mêmes commandes.

**Comment by ghost** [comment]
à priori une erreur à la compilation : KeyError: 'TCL_LIBRARY'. J'utilise une version de python 3.6.2 en Windows 10

**Comment by pierreporte** [comment]
Tu peux poster la sortie complète ?

Je vais refaire une machine virtuelle pour voir comment ça se passe.

**Comment by ghost** [comment]
à priori il faut positionner dans le setup.py ça en adaptant par rapport à la position exacte. Je jette un coup d'oeil

import os
os.environ['TCL_LIBRARY'] = "C:\\Program Files\\Python35\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Program Files\\Python35\\tcl\\tk8.6"

**Comment by pierreporte** [comment]
Est-ce qu’au moins le programme se lance lorsqu’il n’est pas compilé ?

**Comment by ghost** [comment]
Non

```
C:\Users\cyrille\Documents\bornrep>bornrep.py
Traceback (most recent call last):
  File "C:\Users\cyrille\Documents\bornrep\bornrep.py", line 26, in <module>
    Application().mainloop()
  File "C:\Users\cyrille\Documents\bornrep\interface.py", line 61, in __init__
    Image.new("RGBA", (1, 1)).save(self.fichier_prévisualisation.name)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\Image.py", line 1823, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\cyrille\\AppData\\Local\\Temp\\bornrepzygmcguv.png'

```

**Comment by ghost** [comment]
Au niveau de la compilation ça se passe de la façon suivante : 

running build
running build_exe
Traceback (most recent call last):
  File "C:\Users\cyrille\Documents\bornrep\setup.py", line 30, in <module>
    executables = executables)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 621, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 340, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 653, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 416, in _LoadModule
    namespace)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 485, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 463, in _LoadModule
    self._RunHook("load", module.name, module)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 536, in _RunHook
    method(self, *args)
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\hooks.py", line 613, in load_tkinter
    tclSourceDir = os.environ["TCL_LIBRARY"]
  File "C:\Users\cyrille\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TCL_LIBRARY'

**Comment by pierreporte** [comment]
Je vais tester avec une machine virtuelle sous Windows 10.

J’ai trouvé la solution du bug des fichiers temporaires : https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

**Comment by ghost** [comment]
comme précisé, un binaire serait peut être intéressant avec un package d'installation.
